production:
  adapter: postgresql
  host: 198.211.127.34
  username: 'root'
  password: 'WBOY64SLe7tYv1ST'
  database: 'db'
  port: 49157
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: e10_cms_development
  pool: 5
  username: e10
  password:

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: e10_cms_test
  pool: 5
  username: e10
  password:

