production:
  adapter: mysql2
  host: localhost
  username: 'rails'
  password: 'yv4auY6myt'
  database: 'rails'

development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: e10_cms_development
  pool: 5
  username: e10
  password:

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: e10_cms_test
  pool: 5
  username: e10
  password:

